<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Buscador.Infrastructure\Buscador.Infrastructure.csproj" />
    <ProjectReference Include="..\Buscador.Application\Buscador.Application.csproj" />
    <ProjectReference Include="..\Buscador.Domain\Buscador.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
