using Buscador.Domain.Animais;

namespace Buscador.Application.Funcionalidades.PopularAnimais;

public static class DadosSementeAnimal
{
    public static readonly IReadOnlyList<Animal> Animais = new[]
    {
        Animal.Criar(
            nomeComum: "Leão",
            nomeCientifico: "Panthera leo",
            descricao: "O leão é o felino mais social e vive em grupos chamados alcateias. Mamífero carnívoro de grande porte, domina a paisagem africana com seu porte majestoso. Famoso pelo rugido poderoso que pode ser ouvido a quilômetros de distância.",
            caracteristicas: "Pelagem dourada ou marrom-clara, os machos possuem uma juba volumosa ao redor da cabeça e pescoço. Corpo musculoso e compacto, cabeça grande com mandíbulas poderosas. Olhos amarelos brilhantes e dentes caninos até 7 cm.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Savana,
            distribuicaoGeografica: "Encontrado principalmente na África subsaariana, com pequena população na Índia. Concentra-se em savanas, pradarias e florestas abertas.",
            statusConservacao: StatusConservacao.Vulneravel,
            tags: new[] { "felino", "predador", "mamífero", "social", "majestoso" },
            curiosidades: "Os leões dormem até 20 horas por dia. Apenas o leão possui uma juba, que serve para atrair fêmeas e intimidar rivais. As leonas fazem a maior parte da caça enquanto os machos defendem o território."
        ),
        Animal.Criar(
            nomeComum: "Lobo",
            nomeCientifico: "Canis lupus",
            descricao: "O lobo é um canídeo selvagem inteligente e altamente social que caça em matilhas coordenadas. Ancestral direto do cão doméstico, o lobo é um predador de topo em seus habitats. Símbolo de liberdade e selvageria nas culturas humanas.",
            caracteristicas: "Pelagem espessa variando de cinza, marrom e preto, adaptada ao clima frio. Corpo robusto e patas longas para corridas de longa distância, podem atingir velocidades de 40 km/h. Focinho proeminente e orelhas eretas.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Distribuído pelo hemisfério norte, principalmente na América do Norte, Europa e Ásia. Habita florestas boreais, tundras e montanhas.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "canídeo", "predador", "social", "inteligente", "selvagem" },
            curiosidades: "Os lobos caçam em matilhas lideradas por um casal alfa. Possuem um sistema de comunicação sofisticado baseado em uivos, rosnados e linguagem corporal. Podem viajar até 40 km em um dia caçando."
        ),
        Animal.Criar(
            nomeComum: "Golfinho",
            nomeCientifico: "Tursiops truncatus",
            descricao: "O golfinho-nariz-de-garrafa é um cetáceo altamente inteligente conhecido pela sua brincadeira e curiosidade. Mamífero aquático que vive em grupos sociais complexos chamados pods. Reconhecido por sua capacidade de eciolocalização sofisticada.",
            caracteristicas: "Corpo aerodinâmico cinza carvão dorsalmente e mais claro ventralmente. Cabeça arredondada com um bico curto e robusto distintivo. Barbatanas dorsal e laterais bem desenvolvidas, cauda bifurcada.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Oceano,
            distribuicaoGeografica: "Encontrado em águas temperadas e tropicais dos oceanos Atlântico, Pacífico e Índico. Habita principalmente águas costeiras e baías.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "cetáceo", "inteligente", "aquático", "social", "brincalhão" },
            curiosidades: "Golfinhos conseguem reconhecer a si mesmos em espelhos, demonstrando autoconsciência. Usam eciolocalização emitindo cliques que ricocheteiam nos objetos para navegar e caçar. Frequentemente resgatam humanos e ajudam-se mutuamente."
        ),
        Animal.Criar(
            nomeComum: "Águia-real",
            nomeCientifico: "Aquila chrysaetos",
            descricao: "A águia-real é uma ave de rapina magnífica com visão extremamente aguçada e garras poderosas. Predador de topo aéreo capaz de detectar presas a quilômetros de distância. Símbolo de poder e liberdade em muitas culturas.",
            caracteristicas: "Plumagem marrom-escura com manchas douradas na cabeça e nuca, daí o nome 'chrysaetos'. Asas longas e largas, corpo musculoso e garras letais de até 5 cm. Bico curvado e poderoso, olhos amarelos penetrantes.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Montanha,
            distribuicaoGeografica: "Distribuída pelo hemisfério norte através de montanhas e regiões áridas da América do Norte, Europa e Ásia. Habita picos de montanhas e escarpas rochosas.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "ave", "predador", "voo", "visão-aguçada", "majestosa" },
            curiosidades: "Águias-reais podem voar a velocidades de até 200 km/h em mergulho. Seus olhos são 4 a 8 vezes mais aguçados que os humanos. Podem carregar presas pesando até 4 kg com suas garras poderosas."
        ),
        Animal.Criar(
            nomeComum: "Cobra-real",
            nomeCientifico: "Python regius",
            descricao: "A cobra-real é uma serpente constritora dócil originária da África Ocidental. Popular em cativeiro, ganhou seu nome pela crença de que seria a cobra do rei. Não é venenosa, mata suas presas por constrição.",
            caracteristicas: "Corpo robusto variando em cores de marrom, dourado, amarelo e preto. Cabeça triangular pequena com boca extensível, corpo cilíndrico com padrões pretos e brancos. Atinge até 1,5 metros de comprimento.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Originária da África Ocidental, principalmente em regiões de savana e floresta. Encontrada em países como Gana, Benin, Togo e Nigéria.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "réptil", "constrictora", "cobra", "dócil", "exótica" },
            curiosidades: "Cobras-reais podem permanecer semanas sem comer. Matam suas presas envolvendo-as e sufocando-as lentamente. Enrolam-se em uma bola defensiva quando ameaçadas, daí o nome 'regius'."
        ),
        Animal.Criar(
            nomeComum: "Sapo-comum",
            nomeCientifico: "Rana temporaria",
            descricao: "O sapo-comum é um anfíbio europeu que passa parte de sua vida em água e parte em terra seca. Fundamental para o controle de insetos e importante indicador da saúde ambiental. Metamorfose impressionante de girino para sapo adulto.",
            caracteristicas: "Pele áspera castanho-avermelhada a cinzenta com padrão reticulado. Corpo robusto, olhos salientes com pupila horizontal, tímpano visível atrás dos olhos. Patas traseiras longas adaptadas para saltos, patas dianteiras curtas.",
            dieta: Dieta.Onivoro,
            habitat: Habitat.AguaDoce,
            distribuicaoGeografica: "Nativo da Europa, encontrado da Grã-Bretanha até o Cáucaso. Habita lagoas, brejos, zonas húmidas e florestas úmidas.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "anfíbio", "insectívoro", "aquático", "metamorfose", "verde" },
            curiosidades: "Girinos respiram através de brânquias enquanto sapos adultos respiram pulmões e pele. Durante amplexo, múltiplos machos podem agrupando-se em volta de uma fêmea. Suas peles secretam compostos antimicrobianos."
        ),
        Animal.Criar(
            nomeComum: "Tubarão-branco",
            nomeCientifico: "Carcharodon carcharias",
            descricao: "O tubarão-branco é o maior peixe predador do mundo e um dos mais antigos predadores de topo marinhos. Máquina de caça perfeita com sentidos refinados e velocidade impressionante. Símbolo da força selvagem e do mistério oceânico.",
            caracteristicas: "Corpo hidrodinâmico cinza-azulado dorsalmente e branco ventralmente, com mancha preta sob a nadadeira peitoral. Boca enorme com até 3000 dentes triangulares serrilhados dispostos em fileiras. Nadadeira dorsal triangular proeminente.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Oceano,
            distribuicaoGeografica: "Encontrado em todos os oceanos, principalmente em águas temperadas. Habita águas costeiras e profundas onde há foca e leão-marinho.",
            statusConservacao: StatusConservacao.Vulneravel,
            tags: new[] { "tubarão", "predador-topo", "peixe", "marinho", "formidável" },
            curiosidades: "Tubarões-brancos podem atingir velocidades de 56 km/h em investidas. Seus dentes são constantemente regenerados ao longo da vida. Podem detectar uma gota de sangue em uma piscina olímpica."
        ),
        Animal.Criar(
            nomeComum: "Urso-polar",
            nomeCientifico: "Ursus maritimus",
            descricao: "O urso-polar é o mamífero carnívoro terrestre maior e está perfeitamente adaptado ao ambiente ártico extremo. Excelente nadador com metabolismo único para sobreviver em temperaturas abaixo de -40°C. Enfrentando ameaça de aquecimento global.",
            caracteristicas: "Pelagem branca espessa com subpelo denso para isolamento térmico. Corpo robusto e alongado com patas largas e garras curvas para aderência no gelo. Nariz e lábios pretos, olhos pequenos, orelhas arredondadas.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Polar,
            distribuicaoGeografica: "Circumpolar, encontrado em redor do Ártico, principalmente em regiões com gelo marinho. Distribui-se pelo Alasca, Canadá, Rússia, Groenlândia e Noruega.",
            statusConservacao: StatusConservacao.Vulneravel,
            tags: new[] { "urso", "ártico", "natação", "térmico", "majestoso" },
            curiosidades: "Ursos-polares podem nadar até 100 km em busca de alimento. Seu pelo branco não é realmente branco mas transparente e reflete luz. Caçam focas através de buracos no gelo, esperando pacientemente por horas."
        ),
        Animal.Criar(
            nomeComum: "Elefante-africano",
            nomeCientifico: "Loxodonta africana",
            descricao: "O elefante africano é o maior mamífero terrestre, conhecido pela inteligência excepcional e estrutura social complexa. Herbívoro gentil apesar de seu tamanho impressionante, essencial para manter ecossistemas de savana. Memória proverbial e capacidade de relacionamentos profundos.",
            caracteristicas: "Corpo imenso pesando até 6 toneladas, coberto por pele cinzenta espessa. Orelhas largas como leques para dissipar calor, tromba flexível com 40000 músculos. Presas marfim alongadas, patas colunares que suportam o peso.",
            dieta: Dieta.Herbivoro,
            habitat: Habitat.Savana,
            distribuicaoGeografica: "Nativo da África subsaariana, encontrado em savanas, florestas abertas e semi-áridas. Presente em países como Botsuana, Quênia, Tanzânia e Zimbábue.",
            statusConservacao: StatusConservacao.Vulneravel,
            tags: new[] { "mamífero", "herbívoro", "inteligente", "social", "gigante" },
            curiosidades: "Elefantes vivem em grupos matriarcais liderados pela fêmea mais velha. Podem processar luto e mostram comportamento de empatia com congêneres mortos. Sua tromba contém receptores sensoriais sofisticados e força excepcional."
        ),
        Animal.Criar(
            nomeComum: "Papagaio-militar",
            nomeCientifico: "Ara militaris",
            descricao: "O papagaio-militar é uma arara verde de médio porte encontrada nos Andes. Intelecto excepcional para uma ave, com capacidade de resolver problemas e aprender vocabulário. Ligação social forte com seus parceiros ao longo da vida.",
            caracteristicas: "Plumagem predominantemente verde com manchas vermelhas na testa e asas. Cabeça grande com olho branco penetrante, bico poderoso preto curvado. Cauda longa e rígida, patas cinzentas zigodáctilas para agarrar.",
            dieta: Dieta.Onivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Encontrado nos Andes da América do Sul, principalmente na Bolívia, Peru, Equador e Colômbia. Habita florestas de montanha entre 1500 e 3000 metros de altitude.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "ave", "papagaio", "inteligente", "colorido", "social" },
            curiosidades: "Papagaios-militares podem viver mais de 50 anos. Possuem uma das maiores proporções de cérebro para corpo entre aves. Podem aprender a imitar sons e comunicar-se através de vocalizações complexas."
        ),
        Animal.Criar(
            nomeComum: "Tigre",
            nomeCientifico: "Panthera tigris",
            descricao: "O tigre é o maior felino do mundo e um predador solitário e territorial. Caçador furtivo e poderoso, depende da emboscada para capturar suas presas. Considerado símbolo de força e beleza em várias culturas asiáticas.",
            caracteristicas: "Pelagem laranja-avermelhada com listras pretas verticais únicas em cada indivíduo, semelhantes a impressões digitais. Corpo musculoso e flexível com patas dianteiras potentes. Mandíbulas fortes com caninos de até 8 cm.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Encontrado em fragmentos da Ásia, da Sibéria à Índia e Sudeste Asiático. Habita florestas tropicais, taigas, manguezais e pastagens.",
            statusConservacao: StatusConservacao.EmPerigo,
            tags: new[] { "felino", "predador", "mamífero", "solitário", "listrado" },
            curiosidades: "Diferente de outros felinos, os tigres adoram água e nadam com facilidade. Suas listras também estão presentes na pele, não apenas no pelo. Um rugido de tigre pode ser ouvido a até 3 km de distância."
        ),
        Animal.Criar(
            nomeComum: "Onça-pintada",
            nomeCientifico: "Panthera onca",
            descricao: "A onça-pintada é o maior felino das Américas e o terceiro maior do mundo. Predadora de topo com a mordida mais forte entre os grandes felinos proporcionalmente. Reverenciada por antigas civilizações americanas como símbolo de poder.",
            caracteristicas: "Pelagem amarelo-dourada coberta por rosetas pretas com um ponto central, distinguindo-a do leopardo. Corpo robusto e compacto com cabeça larga e patas fortes. Crânio maciço que abriga músculos mandibulares potentes.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Distribuída do sul dos Estados Unidos até a Argentina, com maior população na Amazônia e no Pantanal. Habita florestas densas, áreas alagadas e cerrados.",
            statusConservacao: StatusConservacao.QuaseAmeacado,
            tags: new[] { "felino", "predador", "mamífero", "manchado", "amazônico" },
            curiosidades: "A onça-pintada mata suas presas perfurando o crânio com uma única mordida. Ao contrário da maioria dos felinos, é exímia nadadora e caça jacarés. Seu nome 'onca' deriva do tupi e significa 'aquele que mata com um salto'."
        ),
        Animal.Criar(
            nomeComum: "Girafa",
            nomeCientifico: "Giraffa camelopardalis",
            descricao: "A girafa é o animal terrestre mais alto do mundo, podendo ultrapassar os 5 metros de altura. Herbívoro tranquilo que se alimenta das copas das árvores inalcançáveis a outros animais. Sua silhueta inconfundível é um ícone das savanas africanas.",
            caracteristicas: "Pescoço extremamente longo coberto por manchas marrons irregulares separadas por linhas claras. Pernas altas e finas, língua azulada de até 50 cm e dois ossículos cobertos de pele no topo da cabeça. Andar gracioso e cadenciado.",
            dieta: Dieta.Herbivoro,
            habitat: Habitat.Savana,
            distribuicaoGeografica: "Nativa da África subsaariana, encontrada em savanas, pastagens e florestas abertas. Presente em países como Quênia, Tanzânia, Namíbia e África do Sul.",
            statusConservacao: StatusConservacao.Vulneravel,
            tags: new[] { "mamífero", "herbívoro", "alto", "manchado", "savana" },
            curiosidades: "Apesar do pescoço enorme, a girafa tem apenas sete vértebras cervicais, o mesmo número que os humanos. Seu coração pesa cerca de 11 kg para bombear sangue até o cérebro. Dorme apenas cerca de 30 minutos por dia, em pequenos cochilos."
        ),
        Animal.Criar(
            nomeComum: "Hipopótamo",
            nomeCientifico: "Hippopotamus amphibius",
            descricao: "O hipopótamo é um grande mamífero semiaquático que passa a maior parte do dia submerso na água. Apesar da aparência tranquila, é considerado um dos animais mais perigosos da África. Vive em grupos e é extremamente territorial.",
            caracteristicas: "Corpo enorme em forma de barril com pele cinza-arroxeada quase sem pelos. Cabeça maciça com mandíbulas que abrem até 150 graus, exibindo caninos de até 50 cm. Patas curtas e robustas, olhos e narinas no topo da cabeça.",
            dieta: Dieta.Herbivoro,
            habitat: Habitat.AguaDoce,
            distribuicaoGeografica: "Encontrado na África subsaariana, em rios, lagos e pântanos. Habita corpos de água doce cercados por pastagens onde pasta à noite.",
            statusConservacao: StatusConservacao.Vulneravel,
            tags: new[] { "mamífero", "herbívoro", "aquático", "territorial", "gigante" },
            curiosidades: "O hipopótamo secreta um líquido avermelhado que funciona como protetor solar e antibiótico natural. Apesar de não saber nadar, caminha e salta no fundo dos rios. Pode correr a até 30 km/h em terra firme apesar do peso."
        ),
        Animal.Criar(
            nomeComum: "Rinoceronte-branco",
            nomeCientifico: "Ceratotherium simum",
            descricao: "O rinoceronte-branco é a maior espécie de rinoceronte e o maior mamífero terrestre depois do elefante. Herbívoro pacífico que pasta em grandes planícies abertas. Sofre intensa pressão da caça ilegal por seus chifres.",
            caracteristicas: "Corpo maciço com pele cinza espessa e dois chifres de queratina no focinho, sendo o frontal o maior. Boca larga e quadrada adaptada para pastar grama rente ao solo. Cabeça grande e alongada com orelhas tubulares móveis.",
            dieta: Dieta.Herbivoro,
            habitat: Habitat.Savana,
            distribuicaoGeografica: "Nativo da África, concentrado na África do Sul, Namíbia e Quênia. Habita savanas e pastagens com água e abrigo disponíveis.",
            statusConservacao: StatusConservacao.QuaseAmeacado,
            tags: new[] { "mamífero", "herbívoro", "chifre", "gigante", "ameaçado" },
            curiosidades: "O nome 'branco' vem de uma corruptela da palavra africânder 'wijd' (largo), referente à boca larga. A subespécie do norte está praticamente extinta, restando apenas duas fêmeas. Pode pesar mais de 2 toneladas e ainda assim correr a 50 km/h."
        ),
        Animal.Criar(
            nomeComum: "Gorila",
            nomeCientifico: "Gorilla beringei",
            descricao: "O gorila-das-montanhas é o maior primata vivo e um dos parentes mais próximos do ser humano. Animal inteligente e gentil que vive em grupos familiares coesos liderados por um macho dominante. Compartilha cerca de 98% do DNA humano.",
            caracteristicas: "Corpo robusto coberto por pelagem preta espessa, com os machos adultos exibindo dorso prateado. Braços longos e musculosos mais compridos que as pernas, peito largo e cabeça grande com crista óssea. Mãos e pés com polegares opositores.",
            dieta: Dieta.Herbivoro,
            habitat: Habitat.Montanha,
            distribuicaoGeografica: "Restrito às florestas montanhosas da África Central, nas fronteiras de Ruanda, Uganda e República Democrática do Congo. Habita florestas densas em altitudes elevadas.",
            statusConservacao: StatusConservacao.EmPerigo,
            tags: new[] { "primata", "herbívoro", "inteligente", "social", "ameaçado" },
            curiosidades: "Os gorilas constroem ninhos novos com folhagem todas as noites para dormir. O macho dominante de dorso prateado decide para onde o grupo se desloca e quando descansa. São capazes de aprender linguagem de sinais em cativeiro."
        ),
        Animal.Criar(
            nomeComum: "Chimpanzé",
            nomeCientifico: "Pan troglodytes",
            descricao: "O chimpanzé é um dos primatas mais inteligentes e o parente vivo mais próximo do ser humano. Animal extremamente social que usa ferramentas e demonstra cultura aprendida entre gerações. Comunica-se por gestos, expressões e vocalizações complexas.",
            caracteristicas: "Corpo coberto por pelagem preta, com face, mãos e pés sem pelos. Braços longos adaptados à locomoção entre árvores, mãos hábeis com polegares opositores. Arcadas supraorbitais salientes e orelhas grandes e proeminentes.",
            dieta: Dieta.Onivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Encontrado na África Central e Ocidental, em florestas tropicais e savanas arborizadas. Presente em países como Gabão, Camarões, Tanzânia e Guiné.",
            statusConservacao: StatusConservacao.EmPerigo,
            tags: new[] { "primata", "onívoro", "inteligente", "social", "ferramentas" },
            curiosidades: "Chimpanzés fabricam ferramentas, como varetas para pescar cupins de seus ninhos. Cada grupo possui tradições culturais próprias transmitidas entre gerações. São capazes de reconhecer-se no espelho e planejar ações futuras."
        ),
        Animal.Criar(
            nomeComum: "Canguru-vermelho",
            nomeCientifico: "Osphranter rufus",
            descricao: "O canguru-vermelho é o maior marsupial vivo e um símbolo da Austrália. Locomove-se por saltos potentes que economizam energia em longas distâncias. Vive em grupos chamados mobs e está bem adaptado às regiões áridas do interior australiano.",
            caracteristicas: "Pelagem avermelhada nos machos e acinzentada nas fêmeas, com corpo musculoso e cauda longa e grossa usada como apoio. Patas traseiras enormes e elásticas, patas dianteiras curtas. As fêmeas possuem uma bolsa ventral para os filhotes.",
            dieta: Dieta.Herbivoro,
            habitat: Habitat.Deserto,
            distribuicaoGeografica: "Endêmico da Austrália, distribuído pelas planícies áridas e semiáridas do interior do continente. Evita apenas as florestas mais densas e o litoral mais úmido.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "marsupial", "herbívoro", "saltador", "australiano", "social" },
            curiosidades: "Um canguru-vermelho pode saltar mais de 8 metros de uma só vez e atingir 60 km/h. A cauda funciona como um quinto membro, dando equilíbrio e propulsão. O filhote recém-nascido tem o tamanho de um grão de feijão ao entrar na bolsa."
        ),
        Animal.Criar(
            nomeComum: "Coala",
            nomeCientifico: "Phascolarctos cinereus",
            descricao: "O coala é um marsupial arborícola australiano conhecido por sua aparência dócil e hábitos sonolentos. Alimenta-se quase exclusivamente de folhas de eucalipto, pouco nutritivas e tóxicas para a maioria dos animais. Passa a maior parte do dia dormindo.",
            caracteristicas: "Corpo robusto coberto por pelagem cinza macia e densa, com peito esbranquiçado. Cabeça grande e arredondada com orelhas peludas e nariz largo e escuro. Patas com garras fortes e polegares opositores para escalar troncos.",
            dieta: Dieta.Herbivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Endêmico da costa leste e sul da Austrália, em florestas de eucalipto. Encontrado em estados como Queensland, Nova Gales do Sul e Vitória.",
            statusConservacao: StatusConservacao.Vulneravel,
            tags: new[] { "marsupial", "herbívoro", "arborícola", "australiano", "dócil" },
            curiosidades: "O coala dorme até 20 horas por dia para economizar energia da dieta pobre. Possui impressões digitais quase idênticas às humanas. As folhas de eucalipto são tóxicas, mas seu fígado consegue neutralizar os compostos."
        ),
        Animal.Criar(
            nomeComum: "Panda-gigante",
            nomeCientifico: "Ailuropoda melanoleuca",
            descricao: "O panda-gigante é um urso emblemático conhecido pela pelagem preta e branca e pela dieta quase exclusiva de bambu. Símbolo mundial da conservação da natureza, sua população selvagem se recupera lentamente. Vive solitário em florestas montanhosas da China.",
            caracteristicas: "Pelagem branca com manchas pretas ao redor dos olhos, orelhas e membros. Corpo robusto de urso com um pseudopolegar formado por um osso do pulso, usado para segurar o bambu. Cabeça grande com musculatura mandibular potente.",
            dieta: Dieta.Herbivoro,
            habitat: Habitat.Montanha,
            distribuicaoGeografica: "Endêmico das montanhas do centro da China, principalmente nas províncias de Sichuan, Shaanxi e Gansu. Habita florestas de bambu entre 1200 e 3500 metros de altitude.",
            statusConservacao: StatusConservacao.Vulneravel,
            tags: new[] { "urso", "herbívoro", "bambu", "ameaçado", "símbolo" },
            curiosidades: "O panda come bambu por até 14 horas diárias, consumindo até 38 kg por dia. Apesar de ser classificado como urso, sua dieta é 99% vegetariana. Os filhotes nascem rosados, sem pelo, e pesam cerca de 100 gramas."
        ),
        Animal.Criar(
            nomeComum: "Ornitorrinco",
            nomeCientifico: "Ornithorhynchus anatinus",
            descricao: "O ornitorrinco é um dos animais mais singulares do planeta, um mamífero que põe ovos. Combina características de mamíferos, aves e répteis, intrigando os primeiros naturalistas. Vive em rios e lagos da Austrália, alimentando-se no fundo da água.",
            caracteristicas: "Corpo coberto por pelagem marrom densa e impermeável, com bico achatado semelhante ao de pato. Patas com membranas interdigitais e cauda larga semelhante à do castor. Os machos possuem esporões venenosos nas patas traseiras.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.AguaDoce,
            distribuicaoGeografica: "Endêmico do leste da Austrália e da Tasmânia, em rios e lagos de água doce. Necessita de margens com vegetação onde escava suas tocas.",
            statusConservacao: StatusConservacao.QuaseAmeacado,
            tags: new[] { "monotremado", "mamífero", "aquático", "ovíparo", "singular" },
            curiosidades: "O ornitorrinco é um dos poucos mamíferos venenosos e um dos cinco que põem ovos. Detecta presas por eletrorrecepção, percebendo os campos elétricos dos músculos. Quando descoberto, cientistas acharam que era uma fraude costurada."
        ),
        Animal.Criar(
            nomeComum: "Pinguim-imperador",
            nomeCientifico: "Aptenodytes forsteri",
            descricao: "O pinguim-imperador é a maior espécie de pinguim e a única que se reproduz durante o rigoroso inverno antártico. Ave marinha incapaz de voar, é um exímio mergulhador adaptado ao frio extremo. Os machos incubam os ovos sobre os pés em colônias unidas.",
            caracteristicas: "Plumagem preta nas costas e branca no ventre, com manchas amarelo-douradas nas laterais do pescoço. Corpo robusto e hidrodinâmico, asas transformadas em nadadeiras rígidas. Camada de gordura espessa e penas densas para isolamento térmico.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Polar,
            distribuicaoGeografica: "Endêmico da Antártida, reproduz-se sobre o gelo marinho ao redor do continente. Alimenta-se nas águas geladas do Oceano Antártico.",
            statusConservacao: StatusConservacao.QuaseAmeacado,
            tags: new[] { "ave", "marinho", "antártico", "mergulhador", "social" },
            curiosidades: "Os machos jejuam por até dois meses enquanto incubam o ovo no inverno antártico. Podem mergulhar a mais de 500 metros de profundidade. Para se aquecer, as colônias formam aglomerados que rodam para revezar quem fica na borda gelada."
        ),
        Animal.Criar(
            nomeComum: "Coruja-das-torres",
            nomeCientifico: "Tyto alba",
            descricao: "A coruja-das-torres é uma ave de rapina noturna distribuída por quase todo o planeta. Caçadora silenciosa, localiza presas no escuro graças à audição extraordinária. Importante controladora de roedores em ambientes rurais e urbanos.",
            caracteristicas: "Plumagem dourada e cinza no dorso e branca no ventre, com a característica face em forma de coração. Asas largas com penas serrilhadas que abafam o som do voo. Olhos grandes e escuros voltados para a frente, garras afiadas.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Uma das aves de maior distribuição mundial, presente em todos os continentes exceto a Antártida. Habita campos abertos, bosques, celeiros e construções humanas.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "ave", "predador", "noturno", "silenciosa", "voo" },
            curiosidades: "A coruja-das-torres consegue caçar na escuridão total apenas pelo som, graças a ouvidos assimétricos. Seu voo é praticamente silencioso devido às penas especiais. Engole as presas inteiras e regurgita os ossos em pelotas compactas."
        ),
        Animal.Criar(
            nomeComum: "Flamingo",
            nomeCientifico: "Phoenicopterus roseus",
            descricao: "O flamingo é uma ave aquática esguia conhecida por sua plumagem rosada e suas grandes colônias. Alimenta-se filtrando microrganismos da água com o bico invertido. Realiza danças coletivas sincronizadas durante o cortejo.",
            caracteristicas: "Plumagem rosa-claro a salmão, pernas longas e finas e pescoço sinuoso. Bico curvado para baixo com lamelas que filtram alimento da água. Membranas interdigitais nas patas para caminhar em fundos lamacentos.",
            dieta: Dieta.Onivoro,
            habitat: Habitat.AguaDoce,
            distribuicaoGeografica: "Encontrado na África, sul da Europa e Ásia, em lagos salgados e lagoas rasas. Forma grandes colônias em zonas húmidas e estuários.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "ave", "aquático", "filtrador", "rosado", "colonial" },
            curiosidades: "A cor rosa do flamingo vem dos pigmentos das algas e crustáceos que ele come. Costuma descansar equilibrado em uma única perna para conservar calor corporal. Os filhotes nascem cinzentos e só ficam rosados após meses de alimentação."
        ),
        Animal.Criar(
            nomeComum: "Beija-flor-de-garganta-rubi",
            nomeCientifico: "Archilochus colubris",
            descricao: "O beija-flor é uma das menores aves do mundo, capaz de pairar no ar e voar para trás. Alimenta-se principalmente de néctar, sendo um polinizador essencial de muitas plantas. Seu metabolismo é um dos mais acelerados do reino animal.",
            caracteristicas: "Plumagem verde-iridescente no dorso, com a garganta vermelho-rubi brilhante nos machos. Bico longo e fino adaptado às flores tubulares, língua extensível em forma de canudo. Asas que batem dezenas de vezes por segundo.",
            dieta: Dieta.Onivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Reproduz-se no leste da América do Norte e migra para a América Central no inverno. Habita jardins, bosques e bordas de floresta com flores abundantes.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "ave", "néctar", "polinizador", "minúsculo", "iridescente" },
            curiosidades: "O coração do beija-flor bate até 1200 vezes por minuto durante o voo. Suas asas batem cerca de 50 vezes por segundo, produzindo o zumbido característico. À noite entra em torpor, reduzindo drasticamente o metabolismo para economizar energia."
        ),
        Animal.Criar(
            nomeComum: "Tucano-toco",
            nomeCientifico: "Ramphastos toco",
            descricao: "O tucano-toco é a maior espécie de tucano e uma das aves mais emblemáticas da América do Sul. Reconhecido instantaneamente pelo enorme bico colorido, surpreendentemente leve. Habita matas e cerrados, alimentando-se principalmente de frutas.",
            caracteristicas: "Plumagem preta com peito e garganta brancos e cauda com penas vermelhas. Bico laranja brilhante de até 20 cm com a ponta escura, leve por ser oco internamente. Pele azul ao redor dos olhos e patas com dedos zigodáctilos.",
            dieta: Dieta.Onivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Encontrado na América do Sul, do norte da Argentina ao centro e leste do Brasil. Habita cerrados, matas de galeria, savanas e bordas de floresta.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "ave", "frugívoro", "colorido", "bico-grande", "tropical" },
            curiosidades: "O enorme bico do tucano ajuda a regular sua temperatura corporal, dissipando calor. Apesar do tamanho, o bico é tão leve que a ave consegue voar sem dificuldade. Os tucanos dormem encolhidos, com o bico apoiado sobre as costas."
        ),
        Animal.Criar(
            nomeComum: "Avestruz",
            nomeCientifico: "Struthio camelus",
            descricao: "O avestruz é a maior e mais pesada ave viva do mundo, incapaz de voar mas exímia corredora. Adaptado às planícies áridas africanas, suporta longos períodos sem água. Vive em pequenos grupos liderados por um casal dominante.",
            caracteristicas: "Corpo robusto coberto por plumas, pretas nos machos e acinzentadas nas fêmeas, com pescoço e pernas longas e nuas. Pés com apenas dois dedos, sendo um deles munido de uma garra potente. Olhos grandes, os maiores entre os animais terrestres.",
            dieta: Dieta.Onivoro,
            habitat: Habitat.Savana,
            distribuicaoGeografica: "Nativo das savanas e regiões áridas da África. Encontrado em planícies abertas, semidesertos e pastagens ao sul do Saara.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "ave", "corredor", "onívoro", "gigante", "savana" },
            curiosidades: "O avestruz corre a até 70 km/h, sendo o animal bípede mais veloz do mundo. Seus ovos são os maiores de qualquer ave atual, pesando cerca de 1,5 kg. Ao contrário do mito, não enterra a cabeça na areia quando ameaçado."
        ),
        Animal.Criar(
            nomeComum: "Crocodilo-do-nilo",
            nomeCientifico: "Crocodylus niloticus",
            descricao: "O crocodilo-do-nilo é um dos maiores répteis do mundo e um predador de emboscada formidável. Habita rios e lagos africanos, onde domina como predador de topo. Apesar da ferocidade, exibe cuidado parental notável com os filhotes.",
            caracteristicas: "Corpo robusto coberto por placas ósseas escuras, com cauda longa e musculosa que impulsiona na água. Focinho largo com mandíbulas potentes e dentes cônicos. Olhos e narinas no topo da cabeça, permitindo permanecer quase submerso.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.AguaDoce,
            distribuicaoGeografica: "Distribuído pela África subsaariana, em rios, lagos e pântanos. Presente no vale do Nilo, em Madagascar e em diversas bacias hidrográficas africanas.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "réptil", "predador", "aquático", "emboscada", "ancestral" },
            curiosidades: "A força da mordida do crocodilo-do-nilo é uma das mais potentes do reino animal. A temperatura do ninho determina o sexo dos filhotes. A fêmea carrega os recém-nascidos na boca com extrema delicadeza até a água."
        ),
        Animal.Criar(
            nomeComum: "Tartaruga-verde",
            nomeCientifico: "Chelonia mydas",
            descricao: "A tartaruga-verde é uma das maiores tartarugas marinhas e a única majoritariamente herbívora quando adulta. Realiza longas migrações entre áreas de alimentação e praias de desova. Vive décadas e retorna à praia onde nasceu para reproduzir.",
            caracteristicas: "Casco achatado e hidrodinâmico em tons de oliva e marrom, com membros transformados em nadadeiras. Cabeça pequena e arredondada que não se recolhe no casco. Recebe o nome pela cor esverdeada da gordura sob o casco.",
            dieta: Dieta.Herbivoro,
            habitat: Habitat.Oceano,
            distribuicaoGeografica: "Encontrada em oceanos tropicais e subtropicais de todo o mundo. Alimenta-se em pradarias marinhas costeiras e desova em praias arenosas.",
            statusConservacao: StatusConservacao.EmPerigo,
            tags: new[] { "réptil", "marinho", "herbívoro", "migratório", "ameaçado" },
            curiosidades: "A tartaruga-verde pode percorrer milhares de quilômetros e voltar à praia exata onde nasceu. A temperatura da areia define o sexo dos filhotes. Pode viver mais de 80 anos e levar décadas para atingir a maturidade reprodutiva."
        ),
        Animal.Criar(
            nomeComum: "Camaleão-pantera",
            nomeCientifico: "Furcifer pardalis",
            descricao: "O camaleão-pantera é um réptil arborícola famoso por sua capacidade de mudar de cor. Originário de Madagascar, exibe alguns dos padrões mais vibrantes entre os camaleões. Caça insetos com uma língua projétil de extrema precisão.",
            caracteristicas: "Cores que variam entre azul, vermelho, verde e laranja conforme o humor e a região de origem. Olhos protuberantes que se movem de forma independente, cauda preênsil enrolada e patas em pinça. Língua extensível mais longa que o corpo.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Endêmico das florestas tropicais do norte e leste de Madagascar. Habita áreas costeiras quentes e úmidas com vegetação arbustiva e arbórea.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "réptil", "arborícola", "insetívoro", "colorido", "camuflagem" },
            curiosidades: "O camaleão muda de cor para comunicar humor e temperatura, não apenas para camuflagem. Cada olho se move independentemente, dando visão de 360 graus. Sua língua dispara em centésimos de segundo para capturar a presa."
        ),
        Animal.Criar(
            nomeComum: "Iguana-verde",
            nomeCientifico: "Iguana iguana",
            descricao: "A iguana-verde é um grande réptil arborícola herbívoro das Américas tropicais. Excelente escaladora e nadadora, passa a maior parte do tempo no alto das árvores próximas à água. Popular como animal de estimação exótico em muitos países.",
            caracteristicas: "Corpo coberto por escamas esverdeadas com uma crista de espinhos ao longo do dorso e cauda longa. Papada proeminente sob o queixo e um terceiro olho parietal no topo da cabeça. Garras fortes adaptadas para escalar troncos.",
            dieta: Dieta.Herbivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Nativa da América Central e do Sul, do México ao Brasil. Habita florestas tropicais úmidas próximas a rios, lagos e manguezais.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "réptil", "arborícola", "herbívoro", "escalador", "tropical" },
            curiosidades: "A iguana possui um olho parietal no topo da cabeça que detecta luz e movimento. Pode soltar a cauda para escapar de predadores e regenerá-la depois. Quando ameaçada, salta de árvores altas direto na água para fugir nadando."
        ),
        Animal.Criar(
            nomeComum: "Dragão-de-komodo",
            nomeCientifico: "Varanus komodoensis",
            descricao: "O dragão-de-komodo é o maior lagarto vivo do mundo, um predador dominante em seu habitat insular. Caça presas grandes com mordidas que injetam veneno e bactérias. Pode passar dias farejando carcaças a quilômetros de distância.",
            caracteristicas: "Corpo robusto coberto por escamas reforçadas com pequenos ossos, em tons de cinza e marrom. Cauda musculosa tão longa quanto o corpo, patas fortes com garras curvas. Língua bifurcada amarela usada para detectar odores no ar.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Endêmico de algumas ilhas da Indonésia, como Komodo, Rinca e Flores. Habita savanas secas, florestas tropicais e encostas áridas.",
            statusConservacao: StatusConservacao.EmPerigo,
            tags: new[] { "réptil", "predador", "lagarto", "venenoso", "insular" },
            curiosidades: "O dragão-de-komodo pode comer até 80% do próprio peso em uma única refeição. Possui glândulas de veneno que impedem a coagulação do sangue da presa. Detecta carniça a até 9 km usando a língua bifurcada e o olfato apurado."
        ),
        Animal.Criar(
            nomeComum: "Anaconda-verde",
            nomeCientifico: "Eunectes murinus",
            descricao: "A anaconda-verde é uma das maiores e mais pesadas serpentes do mundo. Constritora semiaquática, vive em rios e pântanos da América do Sul. Mata suas presas por sufocamento, sendo capaz de engolir animais de grande porte.",
            caracteristicas: "Corpo robusto verde-oliva com manchas pretas arredondadas ao longo do dorso. Olhos e narinas no topo da cabeça, permitindo respirar quase submersa. Pode ultrapassar 6 metros de comprimento e pesar mais de 90 kg.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.AguaDoce,
            distribuicaoGeografica: "Encontrada na América do Sul tropical, especialmente na bacia amazônica e no Pantanal. Habita rios de águas lentas, pântanos e áreas alagadas.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "réptil", "constrictora", "cobra", "aquático", "gigante" },
            curiosidades: "A anaconda fêmea é muito maior que o macho, ao contrário da maioria das serpentes. Pode ficar semanas sem comer após uma refeição grande. Dá à luz filhotes vivos, em vez de pôr ovos como a maioria das cobras."
        ),
        Animal.Criar(
            nomeComum: "Salamandra-de-fogo",
            nomeCientifico: "Salamandra salamandra",
            descricao: "A salamandra-de-fogo é um anfíbio terrestre conhecido pelas marcantes manchas amarelas sobre o corpo preto. As cores vivas advertem predadores sobre suas secreções tóxicas. De hábitos noturnos, prefere florestas úmidas e sombrias.",
            caracteristicas: "Corpo preto brilhante com manchas ou faixas amarelas variáveis entre indivíduos. Pele lisa e úmida com glândulas que secretam toxinas defensivas. Cauda longa e cabeça larga com olhos protuberantes e proeminentes glândulas parótidas.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Distribuída pela Europa central e meridional, em florestas úmidas montanhosas. Encontrada próxima a riachos e nascentes onde deposita as larvas.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "anfíbio", "carnívoro", "noturno", "tóxico", "florestal" },
            curiosidades: "As cores vivas da salamandra são um aviso aposemático de sua toxicidade. Ao contrário de muitos anfíbios, várias populações dão à luz larvas ou filhotes já desenvolvidos. Pode viver mais de 20 anos em condições favoráveis."
        ),
        Animal.Criar(
            nomeComum: "Axolote",
            nomeCientifico: "Ambystoma mexicanum",
            descricao: "O axolote é uma salamandra mexicana que mantém características larvais por toda a vida, fenômeno chamado neotenia. Famoso pela extraordinária capacidade de regenerar membros e órgãos. Está criticamente ameaçado em seu habitat natural.",
            caracteristicas: "Corpo alongado com brânquias externas plumosas ao redor da cabeça, em cores que vão do rosado ao escuro. Pele lisa e úmida, cauda achatada lateralmente para nadar. Olhos pequenos sem pálpebras e boca larga em formato de sorriso.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.AguaDoce,
            distribuicaoGeografica: "Endêmico do sistema de lagos de Xochimilco, na Cidade do México. Habita canais e corpos de água doce remanescentes, hoje muito reduzidos.",
            statusConservacao: StatusConservacao.CriticamenteEmPerigo,
            tags: new[] { "anfíbio", "aquático", "neotenia", "regeneração", "ameaçado" },
            curiosidades: "O axolote regenera membros, partes do coração e até do cérebro sem cicatrizes. Mantém as brânquias e a vida aquática por toda a vida, sem se metamorfosear. É amplamente estudado em laboratórios por sua capacidade regenerativa."
        ),
        Animal.Criar(
            nomeComum: "Perereca-de-olhos-vermelhos",
            nomeCientifico: "Agalychnis callidryas",
            descricao: "A perereca-de-olhos-vermelhos é um pequeno anfíbio arborícola das florestas tropicais americanas. Suas cores vivas servem para confundir predadores num truque de defesa. De hábitos noturnos, passa o dia adormecida sobre folhas.",
            caracteristicas: "Corpo verde-vivo com flancos azuis e amarelos e patas laranja vibrantes. Olhos grandes vermelho-rubi com pupila vertical, discos adesivos nas pontas dos dedos. Pele lisa e úmida típica das pererecas arborícolas.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Encontrada nas florestas tropicais da América Central, do sul do México ao Panamá. Habita matas úmidas próximas a lagoas e cursos de água.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "anfíbio", "arborícola", "noturno", "colorido", "tropical" },
            curiosidades: "Ao ser perturbada, a perereca abre os olhos vermelhos para assustar predadores e ganhar tempo para fugir. Os discos adesivos permitem agarrar folhas e galhos lisos. As fêmeas depositam os ovos em folhas suspensas sobre a água."
        ),
        Animal.Criar(
            nomeComum: "Atum-rabilho",
            nomeCientifico: "Thunnus thynnus",
            descricao: "O atum-rabilho é um dos maiores e mais velozes peixes ósseos do oceano. Nadador incansável, percorre milhares de quilômetros em migrações transatlânticas. Muito valorizado na pesca, sofre intensa pressão da sobreexploração.",
            caracteristicas: "Corpo fusiforme e hidrodinâmico, azul-escuro no dorso e prateado no ventre. Nadadeiras retráteis e cauda em forma de meia-lua para impulso potente. Possui circulação especial que mantém o corpo mais quente que a água.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Oceano,
            distribuicaoGeografica: "Encontrado no Oceano Atlântico e no Mar Mediterrâneo. Migra entre áreas de alimentação no norte e zonas de reprodução em águas mais quentes.",
            statusConservacao: StatusConservacao.EmPerigo,
            tags: new[] { "peixe", "marinho", "predador", "veloz", "migratório" },
            curiosidades: "O atum-rabilho pode atingir 70 km/h em arrancadas de caça. É um dos poucos peixes capazes de manter o corpo mais quente que a água ao redor. Pode pesar mais de 600 kg e viver cerca de 40 anos."
        ),
        Animal.Criar(
            nomeComum: "Peixe-palhaço",
            nomeCientifico: "Amphiprion ocellaris",
            descricao: "O peixe-palhaço é um pequeno peixe de recife conhecido pela relação simbiótica com as anêmonas-do-mar. Vive protegido entre os tentáculos urticantes, imune ao seu veneno. Famoso mundialmente após o cinema, é símbolo dos recifes de coral.",
            caracteristicas: "Corpo laranja vivo com três faixas brancas debruadas de preto. Nadadeiras arredondadas e movimento característico de balanço ao nadar. Uma camada de muco especial o protege das picadas da anêmona hospedeira.",
            dieta: Dieta.Onivoro,
            habitat: Habitat.Oceano,
            distribuicaoGeografica: "Encontrado nos recifes de coral do Indo-Pacífico, do Sudeste Asiático à Austrália. Vive associado a anêmonas em águas tropicais rasas e quentes.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "peixe", "marinho", "recife", "simbiose", "colorido" },
            curiosidades: "Todos os peixes-palhaço nascem machos e o dominante do grupo pode se tornar fêmea. A anêmona protege o peixe, que em troca a limpa e afasta predadores. Cada grupo é hierárquico, liderado pela maior fêmea."
        ),
        Animal.Criar(
            nomeComum: "Arraia-manta",
            nomeCientifico: "Mobula birostris",
            descricao: "A arraia-manta é a maior raia do mundo, com nadadeiras que parecem asas planando na água. Filtradora gentil, alimenta-se de plâncton apesar de seu tamanho colossal. Realiza saltos espetaculares para fora da água.",
            caracteristicas: "Corpo achatado em forma de losango, escuro no dorso e claro no ventre, com nadadeiras peitorais enormes. Dois lobos cefálicos que direcionam alimento para a boca larga. Cauda fina sem ferrão venenoso, ao contrário de outras raias.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Oceano,
            distribuicaoGeografica: "Encontrada em oceanos tropicais e subtropicais de todo o mundo. Habita águas costeiras e oceânicas, frequentando estações de limpeza em recifes.",
            statusConservacao: StatusConservacao.EmPerigo,
            tags: new[] { "peixe", "marinho", "filtrador", "gigante", "planador" },
            curiosidades: "A arraia-manta pode ter mais de 7 metros de envergadura entre as nadadeiras. Possui um dos maiores cérebros entre os peixes e demonstra grande inteligência. Salta para fora da água em exibições que podem servir para comunicação ou para remover parasitas."
        ),
        Animal.Criar(
            nomeComum: "Enguia-elétrica",
            nomeCientifico: "Electrophorus electricus",
            descricao: "A enguia-elétrica é um peixe amazônico capaz de gerar fortes descargas elétricas. Usa a eletricidade para atordoar presas, se defender e navegar em águas turvas. Apesar do nome, é mais próxima dos peixes-faca do que das enguias verdadeiras.",
            caracteristicas: "Corpo cilíndrico e alongado cinza-amarelado, com a maior parte ocupada por órgãos elétricos especializados. Boca na ponta do focinho e nadadeira anal longa que ondula para nadar. Pode ultrapassar 2 metros de comprimento.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.AguaDoce,
            distribuicaoGeografica: "Nativa da América do Sul, nas bacias do Amazonas e do Orinoco. Habita rios de águas lentas, igarapés e pântanos de fundo lamacento.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "peixe", "aquático", "elétrico", "predador", "amazônico" },
            curiosidades: "A enguia-elétrica pode liberar descargas de até 860 volts, suficientes para derrubar um cavalo. Precisa subir à superfície para respirar ar atmosférico. Usa pulsos elétricos fracos como um radar para se orientar na água escura."
        ),
        Animal.Criar(
            nomeComum: "Baleia-azul",
            nomeCientifico: "Balaenoptera musculus",
            descricao: "A baleia-azul é o maior animal que já existiu na história do planeta. Apesar do tamanho descomunal, alimenta-se quase exclusivamente de minúsculos crustáceos. Sua população foi dizimada pela caça e recupera-se lentamente.",
            caracteristicas: "Corpo alongado azul-acinzentado, podendo ultrapassar 30 metros e 150 toneladas. Possui barbatanas que filtram o alimento e sulcos ventrais que se expandem ao engolir água. Cabeça larga e achatada com duas aberturas para respirar.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Oceano,
            distribuicaoGeografica: "Encontrada em todos os oceanos do mundo, das águas polares às tropicais. Migra entre áreas de alimentação frias e regiões mais quentes de reprodução.",
            statusConservacao: StatusConservacao.EmPerigo,
            tags: new[] { "cetáceo", "marinho", "filtrador", "gigante", "migratório" },
            curiosidades: "O coração da baleia-azul pode ter o tamanho de um carro pequeno. Seu canto é um dos sons mais altos produzidos por um animal e viaja por centenas de quilômetros. Um filhote ganha cerca de 90 kg por dia só de leite materno."
        ),
        Animal.Criar(
            nomeComum: "Orca",
            nomeCientifico: "Orcinus orca",
            descricao: "A orca, ou baleia-assassina, é o maior membro da família dos golfinhos e um predador de topo dos oceanos. Extremamente inteligente, caça em grupos coordenados com técnicas culturais distintas. Vive em famílias matriarcais muito unidas.",
            caracteristicas: "Corpo robusto preto com manchas brancas marcantes e uma mancha clara atrás do olho. Nadadeira dorsal alta e ereta, especialmente nos machos. Mandíbulas com dentes cônicos potentes e corpo hidrodinâmico extremamente veloz.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Oceano,
            distribuicaoGeografica: "Encontrada em todos os oceanos, das regiões polares aos trópicos. Mais abundante em águas frias e ricas em alimento, próximas às costas.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "cetáceo", "marinho", "predador", "inteligente", "social" },
            curiosidades: "Cada grupo de orcas possui um dialeto próprio de vocalizações transmitido entre gerações. Diferentes populações se especializam em caçar peixes, focas ou até outras baleias. São conhecidas por jogar a presa para o alto antes de comer."
        ),
        Animal.Criar(
            nomeComum: "Polvo-comum",
            nomeCientifico: "Octopus vulgaris",
            descricao: "O polvo-comum é um molusco cefalópode notável pela inteligência e capacidade de camuflagem. Resolve problemas complexos e manipula objetos com seus oito braços flexíveis. É considerado um dos invertebrados mais inteligentes do planeta.",
            caracteristicas: "Corpo mole e bulboso com oito braços cobertos de ventosas sensíveis. Pele que muda instantaneamente de cor e textura para camuflagem ou comunicação. Possui três corações e sangue azulado rico em cobre.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Oceano,
            distribuicaoGeografica: "Encontrado em águas temperadas e tropicais de todo o mundo. Habita fundos rochosos, recifes e tocas em zonas costeiras rasas.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "molusco", "marinho", "inteligente", "camuflagem", "invertebrado" },
            curiosidades: "O polvo tem três corações e o sangue azul devido à hemocianina. Pode espremer o corpo por frestas mínimas, pois não tem ossos. Cada ventosa possui receptores de tato e paladar, dando autonomia parcial aos braços."
        ),
        Animal.Criar(
            nomeComum: "Água-viva-lua",
            nomeCientifico: "Aurelia aurita",
            descricao: "A água-viva-lua é um cnidário gelatinoso translúcido comum em mares de todo o mundo. Deriva ao sabor das correntes, capturando pequenos organismos com seus tentáculos urticantes. Seu corpo é composto por mais de 95% de água.",
            caracteristicas: "Corpo em forma de sino translúcido com quatro gônadas em forma de ferradura visíveis no topo. Curtos tentáculos na borda do umbrela e braços orais que conduzem o alimento à boca central. Movimento pulsante para se deslocar suavemente.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Oceano,
            distribuicaoGeografica: "Distribuída por mares temperados e tropicais de todo o planeta. Habita águas costeiras, baías e estuários, frequentemente em grandes agregações.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "cnidário", "marinho", "gelatinoso", "invertebrado", "planctônico" },
            curiosidades: "A água-viva não possui cérebro, coração ou ossos, apenas uma rede nervosa difusa. Pode pulsar e nadar de forma autônoma mesmo sem um sistema nervoso central complexo. Algumas se reproduzem clonando-se em pólipos fixos no fundo do mar."
        ),
        Animal.Criar(
            nomeComum: "Estrela-do-mar-comum",
            nomeCientifico: "Asterias rubens",
            descricao: "A estrela-do-mar é um equinodermo marinho de simetria radial conhecido por sua impressionante regeneração. Move-se lentamente pelo fundo do mar usando centenas de pés ambulacrários. Predadora de moluscos, abre conchas com força paciente.",
            caracteristicas: "Corpo em forma de estrela, geralmente com cinco braços, em tons de laranja e marrom. Superfície coberta por pequenos espinhos e a face inferior repleta de pés tubulares com ventosas. Boca central na parte de baixo do corpo.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Oceano,
            distribuicaoGeografica: "Encontrada no Atlântico Norte, das costas europeias à América do Norte. Habita fundos rochosos e arenosos de zonas costeiras rasas.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "equinodermo", "marinho", "regeneração", "invertebrado", "predador" },
            curiosidades: "A estrela-do-mar pode regenerar um braço perdido e, em alguns casos, um corpo inteiro a partir dele. Exterioriza o estômago para digerir a presa fora do corpo. Não possui sangue, usando água do mar em seu sistema circulatório."
        ),
        Animal.Criar(
            nomeComum: "Abelha-europeia",
            nomeCientifico: "Apis mellifera",
            descricao: "A abelha-europeia é um inseto social fundamental para a polinização e a produção de mel. Vive em colônias altamente organizadas com divisão de trabalho rigorosa. Comunica a localização das flores por meio de uma dança característica.",
            caracteristicas: "Corpo peludo listrado de marrom e amarelo, dividido em cabeça, tórax e abdômen. Duas asas membranosas de cada lado e patas adaptadas para coletar pólen em cestos. As operárias possuem um ferrão usado em defesa.",
            dieta: Dieta.Herbivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Originária da Europa, África e Ásia, hoje difundida em quase todo o mundo. Habita campos floridos, bosques e áreas agrícolas onde encontra flores.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "inseto", "social", "polinizador", "voador", "colonial" },
            curiosidades: "As abelhas comunicam a posição das flores executando uma dança em forma de oito. Uma colônia pode abrigar dezenas de milhares de indivíduos com uma única rainha. Para produzir meio quilo de mel, voam o equivalente a várias voltas ao mundo."
        ),
        Animal.Criar(
            nomeComum: "Borboleta-monarca",
            nomeCientifico: "Danaus plexippus",
            descricao: "A borboleta-monarca é célebre por suas migrações de milhares de quilômetros entre o Canadá e o México. Suas cores vivas advertem predadores sobre a toxicidade adquirida nas plantas que come quando lagarta. Realiza a viagem ao longo de várias gerações.",
            caracteristicas: "Asas laranja-vivas com nervuras pretas e bordas pontilhadas de branco. Corpo escuro e antenas finas, com envergadura de cerca de 10 cm. As lagartas exibem listras pretas, brancas e amarelas de aviso.",
            dieta: Dieta.Herbivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Nativa das Américas, com grandes populações na América do Norte. Migra para florestas de coníferas no centro do México para passar o inverno.",
            statusConservacao: StatusConservacao.Vulneravel,
            tags: new[] { "inseto", "voador", "migratório", "colorido", "tóxico" },
            curiosidades: "Nenhuma borboleta-monarca completa o ciclo migratório sozinha, que dura várias gerações. Acumulam toxinas das folhas de serralha que as tornam venenosas para predadores. Milhões delas se aglomeram nas mesmas árvores no México todos os anos."
        ),
        Animal.Criar(
            nomeComum: "Formiga-cortadeira",
            nomeCientifico: "Atta sexdens",
            descricao: "A formiga-cortadeira é um inseto social que cultiva fungos a partir de folhas cortadas. Vive em colônias gigantescas com complexa divisão de castas. É considerada um dos animais que mais transformam o ambiente nos trópicos americanos.",
            caracteristicas: "Corpo avermelhado a marrom com mandíbulas serrilhadas potentes para cortar vegetação. Castas de tamanhos variados, das pequenas jardineiras às grandes soldados de cabeça avantajada. Antenas em cotovelo e cintura estreita típica das formigas.",
            dieta: Dieta.Herbivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Nativa das Américas Central e do Sul, abundante no Brasil. Habita florestas tropicais, cerrados e áreas agrícolas onde constrói formigueiros subterrâneos.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "inseto", "social", "herbívoro", "colonial", "cultivador" },
            curiosidades: "As cortadeiras não comem as folhas: usam-nas para cultivar um fungo que serve de alimento. Um formigueiro pode abrigar milhões de indivíduos e atingir vários metros de profundidade. Carregam pedaços de folha muitas vezes maiores que seu próprio corpo."
        ),
        Animal.Criar(
            nomeComum: "Libélula-imperador",
            nomeCientifico: "Anax imperator",
            descricao: "A libélula-imperador é um dos maiores e mais velozes insetos voadores da Europa. Predadora ágil, captura outros insetos em pleno voo com precisão notável. Suas larvas são predadoras aquáticas vorazes antes da metamorfose.",
            caracteristicas: "Corpo alongado com tórax verde e abdômen azul vivo nos machos. Quatro asas membranosas transparentes que se movem de forma independente. Olhos compostos enormes que cobrem quase toda a cabeça, garantindo visão de quase 360 graus.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.AguaDoce,
            distribuicaoGeografica: "Distribuída pela Europa, África e Ásia, próxima a corpos de água doce. Habita lagoas, lagos e rios de águas calmas onde deposita os ovos.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "inseto", "voador", "predador", "aquático", "ágil" },
            curiosidades: "A libélula pode voar para trás, parar no ar e mudar de direção instantaneamente. Captura praticamente todas as presas que persegue, com taxa de sucesso altíssima. Suas larvas vivem anos na água antes de emergir como adultos voadores."
        ),
        Animal.Criar(
            nomeComum: "Louva-a-deus",
            nomeCientifico: "Mantis religiosa",
            descricao: "O louva-a-deus é um inseto predador conhecido pela postura de oração das patas dianteiras. Caçador de emboscada, permanece imóvel até capturar a presa com reflexos fulminantes. Sua camuflagem o confunde com folhas e galhos.",
            caracteristicas: "Corpo alongado verde ou marrom com patas dianteiras dotadas de espinhos para agarrar presas. Cabeça triangular muito móvel, capaz de girar quase 180 graus. Olhos compostos grandes e antenas finas, com asas que permitem voos curtos.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Nativa da Europa, Ásia e África, introduzida em outras regiões. Habita campos, jardins e bordas de floresta com vegetação densa.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "inseto", "predador", "emboscada", "camuflagem", "ágil" },
            curiosidades: "O louva-a-deus é o único inseto capaz de girar a cabeça e olhar por cima do próprio ombro. A fêmea por vezes devora o macho durante ou após o acasalamento. Captura a presa em frações de segundo com as patas dianteiras espinhosas."
        ),
        Animal.Criar(
            nomeComum: "Escorpião-amarelo",
            nomeCientifico: "Tityus serrulatus",
            descricao: "O escorpião-amarelo é um aracnídeo conhecido por seu veneno potente e hábitos noturnos. Predador de pequenos invertebrados, espera a presa em fendas e abrigos escuros. É a espécie de escorpião mais perigosa do Brasil para humanos.",
            caracteristicas: "Corpo amarelado com pernas e cauda da mesma cor, podendo apresentar manchas escuras. Pinças finas e uma cauda segmentada que termina em um ferrão venenoso. Possui quatro pares de patas e dois pedipalpos em forma de pinça.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Floresta,
            distribuicaoGeografica: "Endêmico do Brasil, especialmente nas regiões Sudeste e Nordeste. Habita áreas urbanas, entulhos, frestas e ambientes úmidos e escuros.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "aracnídeo", "predador", "noturno", "venenoso", "invertebrado" },
            curiosidades: "O escorpião-amarelo reproduz-se por partenogênese, gerando filhotes sem necessidade de macho. Brilha em tom esverdeado sob luz ultravioleta. As fêmeas carregam os filhotes nas costas até a primeira muda."
        ),
        Animal.Criar(
            nomeComum: "Aranha-caranguejeira",
            nomeCientifico: "Grammostola rosea",
            descricao: "A aranha-caranguejeira é uma das maiores aranhas do mundo, de temperamento geralmente dócil. Predadora de emboscada, sai à noite para caçar insetos e pequenos vertebrados. Apesar do tamanho intimidador, seu veneno é fraco para humanos.",
            caracteristicas: "Corpo robusto coberto por pelos densos em tons de marrom e rosado. Oito patas grossas e peludas, com quelíceras potentes dotadas de presas. Possui pelos urticantes no abdômen que solta como defesa contra predadores.",
            dieta: Dieta.Carnivoro,
            habitat: Habitat.Deserto,
            distribuicaoGeografica: "Nativa do Chile, Bolívia e Argentina, em regiões áridas e semiáridas. Habita tocas no solo de pastagens secas, desertos e encostas.",
            statusConservacao: StatusConservacao.PoucoPreocupante,
            tags: new[] { "aracnídeo", "predador", "noturno", "peluda", "invertebrado" },
            curiosidades: "A caranguejeira pode passar meses sem comer e viver mais de 20 anos. Solta pelos urticantes do abdômen para irritar predadores. Troca de exoesqueleto periodicamente, podendo regenerar patas perdidas nesse processo."
        )
    };
}