// <auto-generated />
using System;
using Buscador.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Buscador.Infrastructure.Migrations
{
    [DbContext(typeof(ContextoBanco))]
    [Migration("20260615164716_GatilhoVetorBusca")]
    partial class GatilhoVetorBusca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Buscador.Domain.Animais.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caracteristicas")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("caracteristicas");

                    b.Property<string>("Curiosidades")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("curiosidades");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Dieta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dieta");

                    b.Property<string>("DistribuicaoGeografica")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("distribuicao_geografica");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("habitat");

                    b.Property<string>("NomeCientifico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_cientifico");

                    b.Property<string>("NomeComum")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_comum");

                    b.Property<string>("StatusConservacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_conservacao");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<NpgsqlTsVector>("VetorBusca")
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector");

                    b.HasKey("Id");

                    b.ToTable("animais", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
